---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kanso
base-image: ghcr.io/ublue-os/base-main
description: Atomic distro with the niri,noctalia,cachyos-kernel shell using bluebuild
image-version: latest

modules:
  - from-file: default.yml
  
  - type: dnf
    repos:
      copr:
        - bieszczaders/kernel-cachyos
        - bieszczaders/kernel-cachyos-addons
    install:
      packages:
        - scx-scheds
        - scx-tools
        - scx-manager
        - sbsigntools
    replace:
      - from-repo: copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons
        packages:
          - old: zram-generator-defaults
            new: cachyos-settings

  - type: custom-kernel
    kernel: cachyos-lto
    initramfs: true
    source: local
    nvidia: false
    sign:
      key: /tmp/certs/MOK.key
      cert: /usr/share/cert/MOK.pem
      mok-password: universalblue
    secrets:
      - type: file
        source: ./MOK.key
        mount:
          type: file
          destination: /tmp/certs/MOK.key

  - type: systemd
    system:
      enabled:
        - scx_loader.service      